<?php

namespace Stanford\IRB;
/** @var \Stanford\IRB\IRB $module */

echo 'The following is a list of all available attributes that can be pulled from eProtocol for a given protocol event.<br><br>';

$options = [
    ["object" => "panel_id", "description" => "Panel # last assigned", "sample_value" => "3"],
    ["object" => "ptl_number", "description" => "Unique study number", "sample_value" => "147"],
    ["object" => "ptl_dtls_id", "description" => "Unique event number (Modification, renewals, New etc)", "sample_value" => "150127"],
    ["object" => "form_type", "description" => "Describes it the event is a NEW, Revision or Renewal", "sample_value" => "NEW"],
    ["object" => "form_status", "description" => "Each event status", "sample_value" => "APPROVED"],
    ["object" => "status_date", "description" => "Do not use. Last event status update date; All date fields are in DD-MON-YY format", "sample_value" => "01-OCT-17"],
    ["object" => "protocol_category", "description" => "Indicates if the protocol category is Medical or Non-medical", "sample_value" => "NON-MEDICAL"],
    ["object" => "review_type", "description" => "Protocol review type; Includes: EXEMPT, CHARTREVIEW, REGULAR, EXPEDITED, SINGLE IRB, HSR, CHART REVIEW", "sample_value" => "EXEMPT"],
    ["object" => "expedited_paragraph", "description" => "Combined field of all the paragraphs with values separated by delimiter. Applies to EXPEDITED review type (PROTOCOL_TYPE) only", "sample_value" => "Paragraph1 * Paragraph 2  * Paragraph 7"],
    ["object" => "deleted_flag", "description" => "Indicates if the protocol event was deleted", "sample_value" => "N"],
    ["object" => "assigned_date", "description" => "Date assigned to a panel for review", "sample_value" => "04-MAY-15"],
    ["object" => "meeting_date", "description" => "The particular 'meeting date' the protocol is assigned to.", "sample_value" => "27-MAY-15"],
    ["object" => "approval_date", "description" => "The date when the protocol approval is valid from.", "sample_value" => "27-MAY-15"],
    ["object" => "expiration_date", "description" => "The date on which the protocol expires.", "sample_value" => "31-DEC-94"],
    ["object" => "initial_approval_date", "description" => "The date when the protocol was initially approval on.", "sample_value" => "27-MAY-15"],
    ["object" => "protocol_created_by", "description" => "SUNetID of the person creating the protocol", "sample_value" => "newct"],
    ["object" => "created_on", "description" => "Protocol created date", "sample_value" => "29-APR-15"],
    ["object" => "initial_review_type", "description" => "Initial protocol review type", "sample_value" => "EXEMPT"],
    ["object" => "protocol_director", "description" => "Protocol Director’s Name in LastName, First Name format", "sample_value" => "Doe, Jane"],
    ["object" => "pd_sunetid", "description" => "Protocol Director’s SUNetID", "sample_value" => "janedoe"],
    ["object" => "pd_degree", "description" => "Protocol Director’s college degree", "sample_value" => "MD"],
    ["object" => "pd_department_code", "description" => "Protocol Director’s org code", "sample_value" => "XLMY"],
    ["object" => "pd_deptartment_ldap", "description" => "Protocol Director’s department from ldap", "sample_value" => "Economics"],
    ["object" => "pd_dept", "description" => "Protocol Director’s department from local copy in eP", "sample_value" => "Economics"],
    ["object" => "pd_email", "description" => "Protocol Director’s email address", "sample_value" => "rc-eprotocol-test@lists.stanford.edu"],
    ["object" => "pd_position", "description" => "Protocol Director’s primary position at Stanford", "sample_value" => "Assistant Professor"],
    ["object" => "admin_contact", "description" => "Admin contact’s name", "sample_value" => "Doe, Jane"],
    ["object" => "ac_sunetid", "description" => "Admin contact’s sunetid", "sample_value" => "viet"],
    ["object" => "ac_email", "description" => "Admin contact’s  email", "sample_value" => "rc-eprotocol-test@lists.stanford.edu"],
    ["object" => "as_name", "description" => "Academic Sponsor’s name", "sample_value" => "Someval FName"],
    ["object" => "as_position", "description" => "Academic Sponsor’s Position at Stanford", "sample_value" => "Emeritus F"],
    ["object" => "multisitelocations", "description" => "Indicates if this is a multi-site study; From eProtocol GENERAL CHECKLIST - Collaborating Institutions", "sample_value" => ""],
    ["object" => "ptl_title", "description" => "Title of the protocol study", "sample_value" => "ABLTE078NN, Events Following Childhood Trauma"],
    ["object" => "cancer_subjects", "description" => "Indicates if the study involves cancer subjects", "sample_value" => "Y"],
    ["object" => "populations", "description" => "Values from eProtocol Participant Populations section; Delimited by *", "sample_value" => "children******cancer******"],
    ["object" => "children", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "pregnant_woman_and_fetuses", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "neonates", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "abortuses", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "mentallydisabled", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "decisionallychallenged", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "cancersubjects", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "laboratorypersonnel", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "healthyvolunteers", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "Y"],
    ["object" => "students", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "Y"],
    ["object" => "employees", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "Y"],
    ["object" => "prisoners", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "N"],
    ["object" => "other", "description" => "Values from eProtocol Participant Populations section; Y/N", "sample_value" => "Y"],
    ["object" => "drugs_addicting", "description" => "", "sample_value" => "N"],
    ["object" => "drug_investigational", "description" => "Investigational drugs, biologics, reagents, or chemicals? From eProtocol GENERAL CHECKLIST - Drug/Device section", "sample_value" => "N"],
    ["object" => "drugs_commercial", "description" => "Commercially available drugs, reagents, or other chemicals administered to subjects (even if they are not being studied)? from eProtocol GENERAL CHECKLIST - Drug/Device section", "sample_value" => "N"],
    ["object" => "device_investigational", "description" => "Investigational Device / Commercial Device used off-label? From eProtocol GENERAL CHECKLIST - Drug/Device section", "sample_value" => "N"],
    ["object" => "ide_exemptdevice", "description" => "IDE Exempt Device? From eProtocol GENERAL CHECKLIST - Drug/Device section", "sample_value" => "N"],
    ["object" => "clinical_trials_gov", "description" => "Study will be registered on clinicaltrials.gov? From eProtocol GENERAL CHECKLIST", "sample_value" => "N"],
    ["object" => "traininggrant", "description" => "Training Grant? From GENERAL CHECKLIST", "sample_value" => "N"],
    ["object" => "programprojectgrant", "description" => "Program Project Grant? From GENERAL CHECKLIST", "sample_value" => "N"],
    ["object" => "federallysponsoredproject", "description" => "Federally Sponsored Project? From GENERAL CHECKLIST", "sample_value" => "N"],
    ["object" => "isct", "description" => "Industry Sponsored Clinical Trial?", "sample_value" => "N"],
    ["object" => "location_gcrc", "description" => "", "sample_value" => "N"],
    ["object" => "location_va", "description" => "", "sample_value" => "N"],
    ["object" => "studylocation", "description" => "eProtocol Study Location section", "sample_value" => "Stanford University *  * Stanford Hospital and Clinics * LPCH *  *"],
    ["object" => "cancer_center", "description" => "Indicates if Cancer-Related Studies. From eProtocol GENERAL CHECKLIST - Collaborating Institutions: 'Cancer Institute' question", "sample_value" => "N"],
    ["object" => "collaboratinginst", "description" => "Multi-site: Stanford coordinating or PI is lead? From eProtocol GENERAL CHECKLIST - Collaborating Institutions", "sample_value" => "Y"],
    ["object" => "tissues_specimen", "description" => "", "sample_value" => "N*N*N"],
    ["object" => "recruits_at_va", "description" => "The research recruits participants at the Veterans Affairs Palo Alto Health Care System(VAPAHCS); from eProtocol GENERAL CHECKLIST - 'Veterans Affairs (VA)' question", "sample_value" => "N"],
    ["object" => "sponsored_by_va", "description" => "The research is sponsored (i.e., funded) by VAPAHCS. From eProtocol GENERAL CHECKLIST - 'Veterans Affairs (VA)' question", "sample_value" => "N"],
    ["object" => "conducted_by_va", "description" => "The research is conducted by or under the direction of a VA employee (VA-paid or VA Without Compensation (WOC) appointment) while on their VA time. From eProtocol GENERAL CHECKLIST - 'Veterans Affairs (VA)' question", "sample_value" => "N"],
    ["object" => "payment", "description" => "From eProtocol Participant Populations section (8k)", "sample_value" => "N"],
    ["object" => "funding_checklist", "description" => "General Checklist Q11 FSP = Federally Sponsored Project", "sample_value" => "FSP"],
    ["object" => "paragraph_1", "description" => "Category 1 Exempt/Expedited", "sample_value" => ""],
    ["object" => "paragraph_2", "description" => "Category 2 Exempt/Expedited", "sample_value" => ""],
    ["object" => "paragraph_3", "description" => "Category 3 Exempt/Expedited", "sample_value" => ""],
    ["object" => "paragraph_4", "description" => "Category 4 Exempt/Expedited", "sample_value" => ""],
    ["object" => "paragraph_5", "description" => "Category 5 Exempt/Expedited", "sample_value" => ""],
    ["object" => "paragraph_6", "description" => "Category 6 Exempt/Expedited", "sample_value" => ""],
    ["object" => "paragraph_7", "description" => "Category 7 Exempt/Expedited", "sample_value" => ""],
    ["object" => "risk", "description" => "Risk Category; from eProtocol 9a: Overall risk evaluation", "sample_value" => "* Paragraph 2  * Paragraph 3"],
    ["object" => "presented", "description" => "", "sample_value" => "No"],
    ["object" => "submitted_date", "description" => "", "sample_value" => "04-MAY-15"],
    ["object" => "reviewers_assignd_date", "description" => "", "sample_value" => "06-MAY-15"],
    ["object" => "initial_reviewer_assigned_date", "description" => "", "sample_value" => "06-MAY-15"],
    ["object" => "exempt_device", "description" => "Q5. IDE Exempt Device From General Checklist", "sample_value" => "N"],
    ["object" => "consent", "description" => "Q13. Consent form: from consent background", "sample_value" => "Yes"],
    ["object" => "alteration_consent", "description" => "Q13. Alteration of consent: from consent background", "sample_value" => "No"],
    ["object" => "waiver_of_consent", "description" => "Q13. Waiver of consent: from consent background", "sample_value" => "No"],
    ["object" => "waiver_of_doc_consent", "description" => "Q13. Waiver of documentation of consent: from consent background", "sample_value" => "No"],
    ["object" => "shortform_consent", "description" => "Q13. Shortform Consent: from consent background", "sample_value" => "No"],
    ["object" => "assent", "description" => "Q14. Assent form: from assent background", "sample_value" => "No"],
    ["object" => "waiver_of_assent", "description" => "Q14. Waiver of assent: from assent background", "sample_value" => "No"],
    ["object" => "assent_not_applicable", "description" => "Q14. Assent Not Applicable: from assent background", "sample_value" => "No"],
    ["object" => "study_population_8a", "description" => "Target enrollment; from eProtocol Participant Populations section (8a), (i) and (ii))", "sample_value" => "About 1,100 patients will likely take part in study. …"],
    ["object" => "cr_num_of_participants", "description" => "Number of participants entered (or #specimens/ #charts reviewed) since beginning of study.", "sample_value" => "25 patients enrolled"],
    ["object" => "MonitoringEntity", "description" => "From eProtocol Risks section (9.e.8)", "sample_value" => ""]
];
echo '<div style="max-height:1000px; overflow:auto; border:1px solid #ddd; padding:10px; background:#fafafa; font-family:monospace; font-size:13px;">';
echo "<pre><code>";
print_r($options);
echo "</code></pre>";
echo '</div>';
